### ISSUE TITLE
Aula 2 - falha na comunicação entre kafka e NEST-API

### ISSUE THREAD

**Issue by victorhgadioli** [codeedu/imersao-fsfc2#2]
Na hora de subir o código do NEST-API junto com o kafka, apareceu esta informação no terminal do NEST-API. Para ter certeza que não era algo que eu tenha digitado errado, clonei o repositório do curso e ainda assim está dando este problema.

app_1            | [Nest] 65   - 04/06/2021, 10:49:15 PM   [ServerKafka] ERROR [Connection] Connection error: getaddrinfo ENOTFOUND host.docker.internal {"timestamp":"2021-04-06T22:49:15.916Z","logger":"kafkajs","broker":"host.docker.internal:9094","clientId":"code-delivery-server","stack":"Error: getaddrinfo ENOTFOUND host.docker.internal\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"} +24ms

ALguém sabe como resolver?

**Comment by argentinaluiz** [comment]
Olá @victorhgadioli , tudo bem?

Consegue evoluir com erro? Vi que você fechou a PR.

**Comment by victorhgadioli** [comment]
Olá @argentinaluiz 

Consegui sim, mas agora estou com mesmo mesmo problema que o outro Issue: https://github.com/codeedu/imersao-fsfc2/issues/1

O que estava faltando para corrigir este erro especifico era o '127.0.0.1 host.docker.internal' no /etc/hosts

Foi besteria minha, pois não havia visto o README
