### ISSUE TITLE
ao rodar a última instrução recebo um erro ("env.file")

### ISSUE THREAD

**Issue by johnwss** [codeedu/imersao-fsfc2#4]
Olá! segui os passos no readme do repo para executar o arquivo go, como descrito:

docker-compose up -d
# Entrar no container
docker-compose exec app bash
# Rodar a aplicação Golang
go run main.go

Na última instrução, recebo o seguinte retorno:

rror loading .env file
exit status 1

**Comment by elvisvasc** [comment]
> 
> 
> Olá! segui os passos no readme do repo para executar o arquivo go, como descrito:
> 
> docker-compose up -d
> # Entrar no container
> 
> docker-compose exec app bash
> # Rodar a aplicação Golang
> 
> go run main.go
> 
> Na última instrução, recebo o seguinte retorno:
> 
> rror loading .env file
> exit status 1

Você criou o método init() em main.go? Nele tem o carregamento do arquivo .env pelo método godotenv.Load().
Sem isso, as entradas do arquivo .env não conseguem ser lidas.

**Comment by johnwss** [comment]
Obrigado,vou dar uma olhada!
É meu primeiro dia com golang,então é provável que estou deixando passar batido a preparação do ambiente ou dos arquivos comuns.
Vou tentar novamente,obrigado mais uma vez!

**Comment by argentinaluiz** [comment]
Olá @johnwss ,

Você gerou o .env?
