### ISSUE TITLE
Latitude com erro (conversão para float64)

### ISSUE THREAD

**Issue by elvisvasc** [codeedu/imersao-fsfc2#5]
O arquivo simulator/destinations/3.txt está com posições de latitude erradas nas linhas 92,136 e 212, provocando erro de conversão para float64 no método LoadPositions() do arquivo route.go.

![image](https://user-images.githubusercontent.com/40181628/114110963-24db9080-98af-11eb-9c4d-0c61fcbf4872.png)

![image](https://user-images.githubusercontent.com/40181628/114110916-083f5880-98af-11eb-8fa7-8475b38c925c.png)

![image](https://user-images.githubusercontent.com/40181628/114111051-62d8b480-98af-11eb-8b99-796747443de6.png)

**Comment by argentinaluiz** [comment]
Olá @elvisvasc , tudo bem?

Obrigado pelo feedback, já corrigi o arquivo!
